#!/bin/sh

if of_compatible -k raspberrypi,3-model-b; then
	realbootsource="disk0";
elif of_compatible -k linux,dummy-virt; then
	realbootsource="qemu-virt";
fi

if [ -z "$realbootsource" ]; then
	exit
fi

for part in root-A root-B; do
	if [ ! -e "/env/boot/bootsource.${part}" ]; then
		echo "Platform does not support 'bootsource' target, creating workaround boot target for ${part}"
		echo -o /env/boot/bootsource.${part} '#!/bin/sh'
		echo -a /env/boot/bootsource.${part} "boot ${realbootsource}.${part}"
	fi
done
