# -*-makefile-*-
#
# Copyright (C) 2026 by Fernando Luiz Cola <fernando.luiz@pantacor.com>
# Based on rules/mbedtls.make by Bjoern Esser and Michael Olbrich.
#
# For further information about the PTXdist project and license conditions
# see the README file.
#

#
# We provide this package
#
PACKAGES-$(PTXCONF_MBEDTLS_PV) += mbedtls-pv

#
# Paths and names
#
# The 2.28 LTS series with the reduced TLS configuration meta-pantavisor uses
# (recipes-pv/mbedtls/mbedtls_2.28%.bbappend). Pantavisor and libthttp do not
# build against mbedtls 3.x, which the upstream mbedtls package provides.
MBEDTLS_PV_VERSION		:= 2.28.10
MBEDTLS_PV_SHA256		:= 0f2e0525903a89ae1d39ce439d858be66933bda54c5b6102b72a29ed8fe7c088
MBEDTLS_PV			:= mbedtls-pv-$(MBEDTLS_PV_VERSION)
MBEDTLS_PV_SUFFIX		:= tar.gz
MBEDTLS_PV_URL			:= https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v$(MBEDTLS_PV_VERSION).$(MBEDTLS_PV_SUFFIX)
MBEDTLS_PV_SOURCE		:= $(SRCDIR)/mbedtls-$(MBEDTLS_PV_VERSION).$(MBEDTLS_PV_SUFFIX)
MBEDTLS_PV_DIR			:= $(BUILDDIR)/$(MBEDTLS_PV)
MBEDTLS_PV_LICENSE		:= Apache-2.0 OR GPL-2.0-or-later
MBEDTLS_PV_LICENSE_FILES	:= file://LICENSE;md5=379d5819937a6c2f1ef1630d341e026d

# ----------------------------------------------------------------------------
# Prepare
# ----------------------------------------------------------------------------

#
# cmake
#
MBEDTLS_PV_CONF_TOOL		:= cmake
MBEDTLS_PV_CONF_OPT		:= \
	$(CROSS_CMAKE_USR) \
	-DENABLE_PROGRAMS=OFF \
	-DENABLE_TESTING=OFF \
	-DENABLE_ZLIB_SUPPORT=ON \
	-DINSTALL_MBEDTLS_HEADERS=ON \
	-DLINK_WITH_PTHREAD=ON \
	-DLINK_WITH_TRUSTED_STORAGE=OFF \
	-DMBEDTLS_FATAL_WARNINGS=OFF \
	-DUNSAFE_BUILD=OFF \
	-DUSE_PKCS11_HELPER_LIBRARY=OFF \
	-DUSE_SHARED_MBEDTLS_LIBRARY=ON \
	-DUSE_STATIC_MBEDTLS_LIBRARY=OFF

# No quotes around the header name: the PTXdist compiler wrapper word-splits
# these flags without shell quote removal.
MBEDTLS_PV_CFLAGS		:= \
	-I$(MBEDTLS_PV_DIR)/configs \
	-DMBEDTLS_CONFIG_FILE=<config-mini-tls1_1.h> \
	-DMBEDTLS_SSL_PROTO_TLS1_2 \
	-DMBEDTLS_SHA512_C \
	-DMBEDTLS_SSL_SERVER_NAME_INDICATION \
	-DMBEDTLS_REMOVE_ARC4_CIPHERSUITES \
	-DMBEDTLS_REMOVE_3DES_CIPHERSUITES \
	-DMBEDTLS_ECP_NIST_OPTIM \
	-DMBEDTLS_ECP_C \
	-DMBEDTLS_ECDSA_C \
	-DMBEDTLS_PK_PARSE_EC_EXTENDED \
	-DMBEDTLS_ECP_DP_SECP192R1_ENABLED \
	-DMBEDTLS_ECP_DP_SECP224R1_ENABLED \
	-DMBEDTLS_ECP_DP_SECP256R1_ENABLED \
	-DMBEDTLS_ECP_DP_SECP384R1_ENABLED \
	-DMBEDTLS_ECP_DP_SECP521R1_ENABLED \
	-DMBEDTLS_ECP_DP_SECP192K1_ENABLED \
	-DMBEDTLS_ECP_DP_SECP224K1_ENABLED \
	-DMBEDTLS_ECP_DP_SECP256K1_ENABLED \
	-DMBEDTLS_ECP_DP_BP256R1_ENABLED \
	-DMBEDTLS_ECP_DP_BP384R1_ENABLED \
	-DMBEDTLS_ECP_DP_BP512R1_ENABLED \
	-DMBEDTLS_ECP_DP_CURVE25519_ENABLED \
	-DMBEDTLS_ECP_DP_CURVE448_ENABLED \
	-DMBEDTLS_DEBUG_C \
	-DMBEDTLS_ERROR_C

# Consumers (libthttp, libevent-pv, pantavisor) include <mbedtls/config.h> and
# would otherwise see the full default config, mismatching the library's
# struct layouts. Replace it with the same reduced config the library uses.
MBEDTLS_PV_DEFINES := $(patsubst -D%,%,$(filter -DMBEDTLS_%,$(filter-out -DMBEDTLS_CONFIG_FILE=%,$(MBEDTLS_PV_CFLAGS))))

$(STATEDIR)/mbedtls-pv.install:
	@$(call targetinfo)
	@$(call world/install, MBEDTLS_PV)
	@inc=$(MBEDTLS_PV_PKGDIR)/usr/include/mbedtls; \
	install -m 0644 $(MBEDTLS_PV_DIR)/configs/config-mini-tls1_1.h $$inc/config-mini-tls1_1.h && \
	{ \
		echo '/* generated by PTXdist rules/mbedtls-pv.make */'; \
		for d in $(MBEDTLS_PV_DEFINES); do echo "#define $$d"; done; \
		echo '#include "mbedtls/config-mini-tls1_1.h"'; \
	} > $$inc/config.h
	@$(call touch)

# ----------------------------------------------------------------------------
# Target-Install
# ----------------------------------------------------------------------------

$(STATEDIR)/mbedtls-pv.targetinstall:
	@$(call targetinfo)

	@$(call install_init, mbedtls-pv)
	@$(call install_fixup, mbedtls-pv,PRIORITY,optional)
	@$(call install_fixup, mbedtls-pv,SECTION,base)
	@$(call install_fixup, mbedtls-pv,AUTHOR,"Fernando Luiz Cola <fernando.luiz@pantacor.com>")
	@$(call install_fixup, mbedtls-pv,DESCRIPTION,missing)

	@$(call install_lib, mbedtls-pv, 0, 0, 0644, libmbedcrypto)
	@$(call install_lib, mbedtls-pv, 0, 0, 0644, libmbedtls)
	@$(call install_lib, mbedtls-pv, 0, 0, 0644, libmbedx509)

	@$(call install_finish, mbedtls-pv)

	@$(call touch)

# vim: syntax=make
